name: Main

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: SetupNDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r27c
    - name: Build
      id: build
      run: |
        chmod 777 ./build.sh
        ./build.sh
    - name: Upload release
      uses: actions/upload-artifact@v4
      with:
        name: magisk-module-release
        path: out/magisk-module
